source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!
target 'Sprout' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'AFNetworkActivityLogger', :git => 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => '3_0_0'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TwitterKit'
    pod 'TwitterCore'
    pod 'CTFeedback'
    pod 'Onboard'
    pod 'JVFloatLabeledTextField', :git => 'https://github.com/jverdi/JVFloatLabeledTextField.git', :branch => '1.1.1'
    pod 'TPKeyboardAvoiding', :git => 'https://github.com/michaeltyson/TPKeyboardAvoiding.git', :branch => '1.3'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git', :branch => '2.0.3'
    pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git', :branch => '3.8.2'
    pod 'SVPullToRefresh', :git => 'https://github.com/samvermette/SVPullToRefresh.git', :branch => '0.4.1'
    pod 'VTAcknowledgementsViewController'
end
